valid_per: 0.2
test_per: 0.1
lr: 0.001
l2coef: 0.0000001
gamma: 0.99
batch_size: 128
epochs: 10
device: 'cuda'
valid_freq: 2
stop_counter: 3
save_model: true
save_path: './tests/data/'
data_root_path: './tests/data/'
init_weights: './tests/data/E7_test.pt'
session_name: test
online: false
